# Generated by Django 3.2.6 on 2021-08-04 13:40

from django.db import migrations
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_category_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=django.utils.timezone.now, max_length=63),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
