# Generated by Django 3.2.6 on 2021-08-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210805_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(default=0, verbose_name='سرویس یهداشتی'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(related_name='cater', to='listings.Category', verbose_name='دسته بندی'),
        ),
    ]
